// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/photos.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Photo represents a stored photo with metadata
type Photo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_proto_photos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{0}
}

func (x *Photo) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Photo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Photo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Photo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Photo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Photo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// UploadRequest contains the photo data to upload
type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_proto_photos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{1}
}

func (x *UploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadResponse returns the uploaded photo metadata
type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photo         *Photo                 `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_photos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{2}
}

func (x *UploadResponse) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

// DownloadRequest specifies which photo to retrieve
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_photos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// DownloadResponse returns the photo with its data
type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photo         *Photo                 `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_proto_photos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadResponse) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeletePhotoRequest specifies which photo to delete
type DeletePhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePhotoRequest) Reset() {
	*x = DeletePhotoRequest{}
	mi := &file_proto_photos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhotoRequest) ProtoMessage() {}

func (x *DeletePhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhotoRequest.ProtoReflect.Descriptor instead.
func (*DeletePhotoRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePhotoRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// DeletePhotoResponse confirms deletion
type DeletePhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePhotoResponse) Reset() {
	*x = DeletePhotoResponse{}
	mi := &file_proto_photos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhotoResponse) ProtoMessage() {}

func (x *DeletePhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhotoResponse.ProtoReflect.Descriptor instead.
func (*DeletePhotoResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePhotoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetPhotoRequest specifies which photo metadata to retrieve
type GetPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotoRequest) Reset() {
	*x = GetPhotoRequest{}
	mi := &file_proto_photos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoRequest) ProtoMessage() {}

func (x *GetPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetPhotoRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{7}
}

func (x *GetPhotoRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// GetPhotoResponse returns the photo metadata
type GetPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photo         *Photo                 `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotoResponse) Reset() {
	*x = GetPhotoResponse{}
	mi := &file_proto_photos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoResponse) ProtoMessage() {}

func (x *GetPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoResponse.ProtoReflect.Descriptor instead.
func (*GetPhotoResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{8}
}

func (x *GetPhotoResponse) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

// ListPhotosRequest specifies pagination and filtering options
type ListPhotosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhotosRequest) Reset() {
	*x = ListPhotosRequest{}
	mi := &file_proto_photos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosRequest) ProtoMessage() {}

func (x *ListPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosRequest.ProtoReflect.Descriptor instead.
func (*ListPhotosRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{9}
}

func (x *ListPhotosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPhotosRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPhotosRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// ListPhotosResponse returns a paginated list of photos
type ListPhotosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photos        []*Photo               `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhotosResponse) Reset() {
	*x = ListPhotosResponse{}
	mi := &file_proto_photos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosResponse) ProtoMessage() {}

func (x *ListPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosResponse.ProtoReflect.Descriptor instead.
func (*ListPhotosResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{10}
}

func (x *ListPhotosResponse) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *ListPhotosResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CopyPhotoRequest specifies source and destination for copy operation
type CopyPhotoRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceObjectId      string                 `protobuf:"bytes,1,opt,name=source_object_id,json=sourceObjectId,proto3" json:"source_object_id,omitempty"`
	DestinationObjectId string                 `protobuf:"bytes,2,opt,name=destination_object_id,json=destinationObjectId,proto3" json:"destination_object_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CopyPhotoRequest) Reset() {
	*x = CopyPhotoRequest{}
	mi := &file_proto_photos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyPhotoRequest) ProtoMessage() {}

func (x *CopyPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyPhotoRequest.ProtoReflect.Descriptor instead.
func (*CopyPhotoRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{11}
}

func (x *CopyPhotoRequest) GetSourceObjectId() string {
	if x != nil {
		return x.SourceObjectId
	}
	return ""
}

func (x *CopyPhotoRequest) GetDestinationObjectId() string {
	if x != nil {
		return x.DestinationObjectId
	}
	return ""
}

// CopyPhotoResponse returns the copied photo metadata
type CopyPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photo         *Photo                 `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyPhotoResponse) Reset() {
	*x = CopyPhotoResponse{}
	mi := &file_proto_photos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyPhotoResponse) ProtoMessage() {}

func (x *CopyPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyPhotoResponse.ProtoReflect.Descriptor instead.
func (*CopyPhotoResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{12}
}

func (x *CopyPhotoResponse) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

// UpdatePhotoMetadataRequest specifies metadata updates for a photo
type UpdatePhotoMetadataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObjectId       string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	CustomMetadata map[string]string      `protobuf:"bytes,2,rep,name=custom_metadata,json=customMetadata,proto3" json:"custom_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType    string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePhotoMetadataRequest) Reset() {
	*x = UpdatePhotoMetadataRequest{}
	mi := &file_proto_photos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhotoMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhotoMetadataRequest) ProtoMessage() {}

func (x *UpdatePhotoMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhotoMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdatePhotoMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePhotoMetadataRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *UpdatePhotoMetadataRequest) GetCustomMetadata() map[string]string {
	if x != nil {
		return x.CustomMetadata
	}
	return nil
}

func (x *UpdatePhotoMetadataRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// UpdatePhotoMetadataResponse returns the updated photo metadata
type UpdatePhotoMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photo         *Photo                 `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePhotoMetadataResponse) Reset() {
	*x = UpdatePhotoMetadataResponse{}
	mi := &file_proto_photos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhotoMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhotoMetadataResponse) ProtoMessage() {}

func (x *UpdatePhotoMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhotoMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdatePhotoMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePhotoMetadataResponse) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

// GenerateSignedUrlRequest specifies parameters for signed URL generation
type GenerateSignedUrlRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ObjectId          string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ExpirationSeconds int64                  `protobuf:"varint,2,opt,name=expiration_seconds,json=expirationSeconds,proto3" json:"expiration_seconds,omitempty"`
	Method            string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateSignedUrlRequest) Reset() {
	*x = GenerateSignedUrlRequest{}
	mi := &file_proto_photos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedUrlRequest) ProtoMessage() {}

func (x *GenerateSignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedUrlRequest.ProtoReflect.Descriptor instead.
func (*GenerateSignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{15}
}

func (x *GenerateSignedUrlRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GenerateSignedUrlRequest) GetExpirationSeconds() int64 {
	if x != nil {
		return x.ExpirationSeconds
	}
	return 0
}

func (x *GenerateSignedUrlRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// GenerateSignedUrlResponse returns the signed URL and expiration time
type GenerateSignedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedUrl     string                 `protobuf:"bytes,1,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSignedUrlResponse) Reset() {
	*x = GenerateSignedUrlResponse{}
	mi := &file_proto_photos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedUrlResponse) ProtoMessage() {}

func (x *GenerateSignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedUrlResponse.ProtoReflect.Descriptor instead.
func (*GenerateSignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateSignedUrlResponse) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *GenerateSignedUrlResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// PhotoExistsRequest specifies which photo to check for existence
type PhotoExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoExistsRequest) Reset() {
	*x = PhotoExistsRequest{}
	mi := &file_proto_photos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoExistsRequest) ProtoMessage() {}

func (x *PhotoExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoExistsRequest.ProtoReflect.Descriptor instead.
func (*PhotoExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{17}
}

func (x *PhotoExistsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// PhotoExistsResponse returns whether the photo exists
type PhotoExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoExistsResponse) Reset() {
	*x = PhotoExistsResponse{}
	mi := &file_proto_photos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoExistsResponse) ProtoMessage() {}

func (x *PhotoExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoExistsResponse.ProtoReflect.Descriptor instead.
func (*PhotoExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{18}
}

func (x *PhotoExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// ListDirectoriesRequest specifies the prefix and pagination for listing directories
type ListDirectoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoriesRequest) Reset() {
	*x = ListDirectoriesRequest{}
	mi := &file_proto_photos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoriesRequest) ProtoMessage() {}

func (x *ListDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoriesRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{19}
}

func (x *ListDirectoriesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// ListDirectoriesResponse returns directory prefixes
type ListDirectoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []string               `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoriesResponse) Reset() {
	*x = ListDirectoriesResponse{}
	mi := &file_proto_photos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoriesResponse) ProtoMessage() {}

func (x *ListDirectoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoriesResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{20}
}

func (x *ListDirectoriesResponse) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

// StreamingUploadRequest is sent as a stream of chunks for large uploads
type StreamingUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*StreamingUploadRequest_Metadata
	//	*StreamingUploadRequest_Chunk
	Data          isStreamingUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingUploadRequest) Reset() {
	*x = StreamingUploadRequest{}
	mi := &file_proto_photos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingUploadRequest) ProtoMessage() {}

func (x *StreamingUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingUploadRequest.ProtoReflect.Descriptor instead.
func (*StreamingUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{21}
}

func (x *StreamingUploadRequest) GetData() isStreamingUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamingUploadRequest) GetMetadata() *PhotoMetadata {
	if x != nil {
		if x, ok := x.Data.(*StreamingUploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *StreamingUploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*StreamingUploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isStreamingUploadRequest_Data interface {
	isStreamingUploadRequest_Data()
}

type StreamingUploadRequest_Metadata struct {
	// metadata is sent in the first message only
	Metadata *PhotoMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type StreamingUploadRequest_Chunk struct {
	// chunk contains a portion of the photo data
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*StreamingUploadRequest_Metadata) isStreamingUploadRequest_Data() {}

func (*StreamingUploadRequest_Chunk) isStreamingUploadRequest_Data() {}

// PhotoMetadata contains info about the photo being uploaded
type PhotoMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoMetadata) Reset() {
	*x = PhotoMetadata{}
	mi := &file_proto_photos_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoMetadata) ProtoMessage() {}

func (x *PhotoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoMetadata.ProtoReflect.Descriptor instead.
func (*PhotoMetadata) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{22}
}

func (x *PhotoMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PhotoMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// StreamingDownloadRequest specifies which photo to download
type StreamingDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingDownloadRequest) Reset() {
	*x = StreamingDownloadRequest{}
	mi := &file_proto_photos_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingDownloadRequest) ProtoMessage() {}

func (x *StreamingDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingDownloadRequest.ProtoReflect.Descriptor instead.
func (*StreamingDownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{23}
}

func (x *StreamingDownloadRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// StreamingDownloadResponse is streamed back in chunks
type StreamingDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*StreamingDownloadResponse_Metadata
	//	*StreamingDownloadResponse_Chunk
	Data          isStreamingDownloadResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingDownloadResponse) Reset() {
	*x = StreamingDownloadResponse{}
	mi := &file_proto_photos_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingDownloadResponse) ProtoMessage() {}

func (x *StreamingDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photos_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingDownloadResponse.ProtoReflect.Descriptor instead.
func (*StreamingDownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_photos_proto_rawDescGZIP(), []int{24}
}

func (x *StreamingDownloadResponse) GetData() isStreamingDownloadResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamingDownloadResponse) GetMetadata() *Photo {
	if x != nil {
		if x, ok := x.Data.(*StreamingDownloadResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *StreamingDownloadResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*StreamingDownloadResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isStreamingDownloadResponse_Data interface {
	isStreamingDownloadResponse_Data()
}

type StreamingDownloadResponse_Metadata struct {
	// metadata is sent in the first message only
	Metadata *Photo `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type StreamingDownloadResponse_Chunk struct {
	// chunk contains a portion of the photo data
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*StreamingDownloadResponse_Metadata) isStreamingDownloadResponse_Data() {}

func (*StreamingDownloadResponse_Chunk) isStreamingDownloadResponse_Data() {}

var File_proto_photos_proto protoreflect.FileDescriptor

const file_proto_photos_proto_rawDesc = "" +
	"\n" +
	"\x12proto/photos.proto\x12\x06photos\x1a\x1cgoogle/api/annotations.proto\"\xc0\x01\n" +
	"\x05Photo\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"b\n" +
	"\rUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"5\n" +
	"\x0eUploadResponse\x12#\n" +
	"\x05photo\x18\x01 \x01(\v2\r.photos.PhotoR\x05photo\".\n" +
	"\x0fDownloadRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"K\n" +
	"\x10DownloadResponse\x12#\n" +
	"\x05photo\x18\x01 \x01(\v2\r.photos.PhotoR\x05photo\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"1\n" +
	"\x12DeletePhotoRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"/\n" +
	"\x13DeletePhotoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x0fGetPhotoRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"7\n" +
	"\x10GetPhotoResponse\x12#\n" +
	"\x05photo\x18\x01 \x01(\v2\r.photos.PhotoR\x05photo\"g\n" +
	"\x11ListPhotosRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"c\n" +
	"\x12ListPhotosResponse\x12%\n" +
	"\x06photos\x18\x01 \x03(\v2\r.photos.PhotoR\x06photos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"p\n" +
	"\x10CopyPhotoRequest\x12(\n" +
	"\x10source_object_id\x18\x01 \x01(\tR\x0esourceObjectId\x122\n" +
	"\x15destination_object_id\x18\x02 \x01(\tR\x13destinationObjectId\"8\n" +
	"\x11CopyPhotoResponse\x12#\n" +
	"\x05photo\x18\x01 \x01(\v2\r.photos.PhotoR\x05photo\"\x80\x02\n" +
	"\x1aUpdatePhotoMetadataRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12_\n" +
	"\x0fcustom_metadata\x18\x02 \x03(\v26.photos.UpdatePhotoMetadataRequest.CustomMetadataEntryR\x0ecustomMetadata\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x1aA\n" +
	"\x13CustomMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x1bUpdatePhotoMetadataResponse\x12#\n" +
	"\x05photo\x18\x01 \x01(\v2\r.photos.PhotoR\x05photo\"~\n" +
	"\x18GenerateSignedUrlRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12-\n" +
	"\x12expiration_seconds\x18\x02 \x01(\x03R\x11expirationSeconds\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"Y\n" +
	"\x19GenerateSignedUrlResponse\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x01 \x01(\tR\tsignedUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"1\n" +
	"\x12PhotoExistsRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"-\n" +
	"\x13PhotoExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"0\n" +
	"\x16ListDirectoriesRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"5\n" +
	"\x17ListDirectoriesResponse\x12\x1a\n" +
	"\bprefixes\x18\x01 \x03(\tR\bprefixes\"m\n" +
	"\x16StreamingUploadRequest\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.photos.PhotoMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"N\n" +
	"\rPhotoMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"7\n" +
	"\x18StreamingDownloadRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"h\n" +
	"\x19StreamingDownloadResponse\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.photos.PhotoH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data2\xf5\x02\n" +
	"\vByteService\x12U\n" +
	"\x06Upload\x12\x15.photos.UploadRequest\x1a\x16.photos.UploadResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/photos/upload\x12f\n" +
	"\bDownload\x12\x17.photos.DownloadRequest\x1a\x18.photos.DownloadResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/photos/{object_id}/download\x12K\n" +
	"\x0fStreamingUpload\x12\x1e.photos.StreamingUploadRequest\x1a\x16.photos.UploadResponse(\x01\x12Z\n" +
	"\x11StreamingDownload\x12 .photos.StreamingDownloadRequest\x1a!.photos.StreamingDownloadResponse0\x012\x93\a\n" +
	"\x0eLibraryService\x12f\n" +
	"\vDeletePhoto\x12\x1a.photos.DeletePhotoRequest\x1a\x1b.photos.DeletePhotoResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/v1/photos/{object_id}\x12]\n" +
	"\bGetPhoto\x12\x17.photos.GetPhotoRequest\x1a\x18.photos.GetPhotoResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/photos/{object_id}\x12W\n" +
	"\n" +
	"ListPhotos\x12\x19.photos.ListPhotosRequest\x1a\x1a.photos.ListPhotosResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/photos\x12o\n" +
	"\tCopyPhoto\x12\x18.photos.CopyPhotoRequest\x1a\x19.photos.CopyPhotoResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/photos/{source_object_id}/copy\x12\x8a\x01\n" +
	"\x13UpdatePhotoMetadata\x12\".photos.UpdatePhotoMetadataRequest\x1a#.photos.UpdatePhotoMetadataResponse\"*\x82\xd3\xe4\x93\x02$:\x01*2\x1f/v1/photos/{object_id}/metadata\x12\x86\x01\n" +
	"\x11GenerateSignedUrl\x12 .photos.GenerateSignedUrlRequest\x1a!.photos.GenerateSignedUrlResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/photos/{object_id}/signed-url\x12m\n" +
	"\vPhotoExists\x12\x1a.photos.PhotoExistsRequest\x1a\x1b.photos.PhotoExistsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/photos/{object_id}/exists\x12k\n" +
	"\x0fListDirectories\x12\x1e.photos.ListDirectoriesRequest\x1a\x1f.photos.ListDirectoriesResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/directoriesB\x0eZ\fphotos/protob\x06proto3"

var (
	file_proto_photos_proto_rawDescOnce sync.Once
	file_proto_photos_proto_rawDescData []byte
)

func file_proto_photos_proto_rawDescGZIP() []byte {
	file_proto_photos_proto_rawDescOnce.Do(func() {
		file_proto_photos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_photos_proto_rawDesc), len(file_proto_photos_proto_rawDesc)))
	})
	return file_proto_photos_proto_rawDescData
}

var file_proto_photos_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_photos_proto_goTypes = []any{
	(*Photo)(nil),                       // 0: photos.Photo
	(*UploadRequest)(nil),               // 1: photos.UploadRequest
	(*UploadResponse)(nil),              // 2: photos.UploadResponse
	(*DownloadRequest)(nil),             // 3: photos.DownloadRequest
	(*DownloadResponse)(nil),            // 4: photos.DownloadResponse
	(*DeletePhotoRequest)(nil),          // 5: photos.DeletePhotoRequest
	(*DeletePhotoResponse)(nil),         // 6: photos.DeletePhotoResponse
	(*GetPhotoRequest)(nil),             // 7: photos.GetPhotoRequest
	(*GetPhotoResponse)(nil),            // 8: photos.GetPhotoResponse
	(*ListPhotosRequest)(nil),           // 9: photos.ListPhotosRequest
	(*ListPhotosResponse)(nil),          // 10: photos.ListPhotosResponse
	(*CopyPhotoRequest)(nil),            // 11: photos.CopyPhotoRequest
	(*CopyPhotoResponse)(nil),           // 12: photos.CopyPhotoResponse
	(*UpdatePhotoMetadataRequest)(nil),  // 13: photos.UpdatePhotoMetadataRequest
	(*UpdatePhotoMetadataResponse)(nil), // 14: photos.UpdatePhotoMetadataResponse
	(*GenerateSignedUrlRequest)(nil),    // 15: photos.GenerateSignedUrlRequest
	(*GenerateSignedUrlResponse)(nil),   // 16: photos.GenerateSignedUrlResponse
	(*PhotoExistsRequest)(nil),          // 17: photos.PhotoExistsRequest
	(*PhotoExistsResponse)(nil),         // 18: photos.PhotoExistsResponse
	(*ListDirectoriesRequest)(nil),      // 19: photos.ListDirectoriesRequest
	(*ListDirectoriesResponse)(nil),     // 20: photos.ListDirectoriesResponse
	(*StreamingUploadRequest)(nil),      // 21: photos.StreamingUploadRequest
	(*PhotoMetadata)(nil),               // 22: photos.PhotoMetadata
	(*StreamingDownloadRequest)(nil),    // 23: photos.StreamingDownloadRequest
	(*StreamingDownloadResponse)(nil),   // 24: photos.StreamingDownloadResponse
	nil,                                 // 25: photos.UpdatePhotoMetadataRequest.CustomMetadataEntry
}
var file_proto_photos_proto_depIdxs = []int32{
	0,  // 0: photos.UploadResponse.photo:type_name -> photos.Photo
	0,  // 1: photos.DownloadResponse.photo:type_name -> photos.Photo
	0,  // 2: photos.GetPhotoResponse.photo:type_name -> photos.Photo
	0,  // 3: photos.ListPhotosResponse.photos:type_name -> photos.Photo
	0,  // 4: photos.CopyPhotoResponse.photo:type_name -> photos.Photo
	25, // 5: photos.UpdatePhotoMetadataRequest.custom_metadata:type_name -> photos.UpdatePhotoMetadataRequest.CustomMetadataEntry
	0,  // 6: photos.UpdatePhotoMetadataResponse.photo:type_name -> photos.Photo
	22, // 7: photos.StreamingUploadRequest.metadata:type_name -> photos.PhotoMetadata
	0,  // 8: photos.StreamingDownloadResponse.metadata:type_name -> photos.Photo
	1,  // 9: photos.ByteService.Upload:input_type -> photos.UploadRequest
	3,  // 10: photos.ByteService.Download:input_type -> photos.DownloadRequest
	21, // 11: photos.ByteService.StreamingUpload:input_type -> photos.StreamingUploadRequest
	23, // 12: photos.ByteService.StreamingDownload:input_type -> photos.StreamingDownloadRequest
	5,  // 13: photos.LibraryService.DeletePhoto:input_type -> photos.DeletePhotoRequest
	7,  // 14: photos.LibraryService.GetPhoto:input_type -> photos.GetPhotoRequest
	9,  // 15: photos.LibraryService.ListPhotos:input_type -> photos.ListPhotosRequest
	11, // 16: photos.LibraryService.CopyPhoto:input_type -> photos.CopyPhotoRequest
	13, // 17: photos.LibraryService.UpdatePhotoMetadata:input_type -> photos.UpdatePhotoMetadataRequest
	15, // 18: photos.LibraryService.GenerateSignedUrl:input_type -> photos.GenerateSignedUrlRequest
	17, // 19: photos.LibraryService.PhotoExists:input_type -> photos.PhotoExistsRequest
	19, // 20: photos.LibraryService.ListDirectories:input_type -> photos.ListDirectoriesRequest
	2,  // 21: photos.ByteService.Upload:output_type -> photos.UploadResponse
	4,  // 22: photos.ByteService.Download:output_type -> photos.DownloadResponse
	2,  // 23: photos.ByteService.StreamingUpload:output_type -> photos.UploadResponse
	24, // 24: photos.ByteService.StreamingDownload:output_type -> photos.StreamingDownloadResponse
	6,  // 25: photos.LibraryService.DeletePhoto:output_type -> photos.DeletePhotoResponse
	8,  // 26: photos.LibraryService.GetPhoto:output_type -> photos.GetPhotoResponse
	10, // 27: photos.LibraryService.ListPhotos:output_type -> photos.ListPhotosResponse
	12, // 28: photos.LibraryService.CopyPhoto:output_type -> photos.CopyPhotoResponse
	14, // 29: photos.LibraryService.UpdatePhotoMetadata:output_type -> photos.UpdatePhotoMetadataResponse
	16, // 30: photos.LibraryService.GenerateSignedUrl:output_type -> photos.GenerateSignedUrlResponse
	18, // 31: photos.LibraryService.PhotoExists:output_type -> photos.PhotoExistsResponse
	20, // 32: photos.LibraryService.ListDirectories:output_type -> photos.ListDirectoriesResponse
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_photos_proto_init() }
func file_proto_photos_proto_init() {
	if File_proto_photos_proto != nil {
		return
	}
	file_proto_photos_proto_msgTypes[21].OneofWrappers = []any{
		(*StreamingUploadRequest_Metadata)(nil),
		(*StreamingUploadRequest_Chunk)(nil),
	}
	file_proto_photos_proto_msgTypes[24].OneofWrappers = []any{
		(*StreamingDownloadResponse_Metadata)(nil),
		(*StreamingDownloadResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_photos_proto_rawDesc), len(file_proto_photos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_photos_proto_goTypes,
		DependencyIndexes: file_proto_photos_proto_depIdxs,
		MessageInfos:      file_proto_photos_proto_msgTypes,
	}.Build()
	File_proto_photos_proto = out.File
	file_proto_photos_proto_goTypes = nil
	file_proto_photos_proto_depIdxs = nil
}
